#ifndef NET_TRANSPORT_TYPES_H
#define NET_TRANSPORT_TYPES_H

#include <stdint.h>

typedef enum
{
  NET_TRANSPORT_TCP = 0,
  NET_TRANSPORT_UDP,
  NET_TRANSPORT_TYPE_COUNT
} net_transport_type_t;

typedef enum
{
  NET_TRANSPORT_STATE_CLOSED = 0,
  NET_TRANSPORT_STATE_CONNECTING,
  NET_TRANSPORT_STATE_CONNECTED,
  NET_TRANSPORT_STATE_CLOSING,
  NET_TRANSPORT_STATE_DISCONNECTED,
  NET_TRANSPORT_STATE_ERROR
} net_transport_state_t;

typedef enum
{
  NET_TRANSPORT_OK = 0,
  NET_TRANSPORT_WOULD_BLOCK = -1,
  NET_TRANSPORT_TIMEOUT = -2,
  NET_TRANSPORT_DISCONNECTED = -3,
  NET_TRANSPORT_NO_SPACE = -4,
  NET_TRANSPORT_INVALID = -5,
  NET_TRANSPORT_INTERNAL_ERROR = -6
} net_transport_result_t;

#define NET_TCP_RX_RING_SIZE          8192U
#define NET_TCP_TX_RING_SIZE          8192U
#define NET_UDP_SLOT_COUNT            8U
#define NET_UDP_MAX_DATAGRAM          1472U
#define NET_RAW_CALLBACK_BUDGET_US    1000U
#define NET_TEST_SERVER_IP0           192U
#define NET_TEST_SERVER_IP1           168U
#define NET_TEST_SERVER_IP2           1U
#define NET_TEST_SERVER_IP3           10U
#define NET_TEST_TCP_PORT             6000U
#define NET_TEST_UDP_PORT             6001U
#define NET_TRANSPORT_SELF_TEST       0U

#endif /* NET_TRANSPORT_TYPES_H */
