#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define PROJECT_LED_ACTIVE_HIGH             1

#define PROJECT_SENSOR_INTERVAL_MS          10U
#define PROJECT_NET_INTERVAL_MS             100U
#define PROJECT_TELEMETRY_INTERVAL_MS       1000U
#define PROJECT_MONITOR_INTERVAL_MS         5000U
#define PROJECT_LED_TOGGLE_INTERVAL_MS      500U

/* FreeRTOS task stack depths are StackType_t elements, not bytes. */
#define PROJECT_SENSOR_TASK_STACK_WORDS     256U
#define PROJECT_CAN_TASK_STACK_WORDS        256U
#define PROJECT_NET_TASK_STACK_WORDS        512U
#define PROJECT_SECURITY_TASK_STACK_WORDS   2048U
#define PROJECT_TELEMETRY_TASK_STACK_WORDS  512U
#define PROJECT_MONITOR_TASK_STACK_WORDS    256U
#define PROJECT_LOGGER_TASK_STACK_WORDS     512U
#define PROJECT_NETIF_TASK_STACK_WORDS      512U

#define PROJECT_SENSOR_TASK_PRIORITY        5U
#define PROJECT_CAN_TASK_PRIORITY           4U
#define PROJECT_NET_TASK_PRIORITY           3U
#define PROJECT_SECURITY_TASK_PRIORITY      2U
#define PROJECT_TELEMETRY_TASK_PRIORITY     2U
#define PROJECT_MONITOR_TASK_PRIORITY       1U
#define PROJECT_LOGGER_TASK_PRIORITY        1U
#define PROJECT_NETIF_TASK_PRIORITY         3U

#define PROJECT_MAX_MONITORED_TASKS         12U
#define PROJECT_RUNTIME_STATS_FREQUENCY_HZ  10000U
#define PROJECT_ENABLE_STACK_OVERFLOW_TEST  0U

#define PROJECT_IPC_SELF_TEST_ENABLE          1U
#define PROJECT_IPC_STRESS_TEST_ENABLE        0U
#define PROJECT_LOG_QUEUE_FULL_TEST_ENABLE    1U

#define PROJECT_CAN_MODE_NORMAL              0U
#define PROJECT_CAN_MODE_INTERNAL_LOOPBACK   1U
#define PROJECT_CAN_MODE PROJECT_CAN_MODE_NORMAL
#define PROJECT_CAN_DIAGNOSTIC_FRAME_LOG_LIMIT  4U
#define PROJECT_CAN_RX_RING_CAPACITY         32U
#define PROJECT_CAN_TX_QUEUE_LENGTH          8U
#define PROJECT_CAN_ISR_MAX_DRAIN            3U
#define PROJECT_CAN_TX_RETRY_MAX             3U
#define PROJECT_CAN_TX_RETRY_DELAY_MS        5U
#define PROJECT_CAN_RECOVERY_MAX_ATTEMPTS    3U
#define PROJECT_CAN_RECOVERY_TIMEOUT_MS      1000U
#define PROJECT_CAN_BUSOFF_TEST_ENABLE       0U
#define PROJECT_CAN_LOOPBACK_FRAME_COUNT     32U
#define PROJECT_CAN_LOOPBACK_TIMEOUT_MS      1000U

#define ENC28J60_USE_SPI_DMA                 0U
#define PROJECT_ENC_LINK_POLL_MS             300U
#define PROJECT_ENC_INIT_RETRY_MS            5000U
#define PROJECT_ENC_MAX_RX_PER_RUN           8U
#define PROJECT_RAW_ETH_TX_INTERVAL_MS       2000U
#define PROJECT_ENC_STATS_INTERVAL_MS        10000U
#define PROJECT_ENC_FRAME_BUFFER_SIZE        1536U

#if ((PROJECT_CAN_MODE != PROJECT_CAN_MODE_NORMAL) && \
     (PROJECT_CAN_MODE != PROJECT_CAN_MODE_INTERNAL_LOOPBACK))
#error "PROJECT_CAN_MODE is invalid"
#endif

#define PROJECT_HWSEC_SELF_TEST_ENABLE        1U
#define PROJECT_HWSEC_DIAGNOSTIC_LOG_ENABLE   1U
#define PROJECT_RNG_SELF_TEST_WORD_COUNT      16U
#define PROJECT_RNG_MAX_RETRY_COUNT           3U

#if (PROJECT_RNG_SELF_TEST_WORD_COUNT < 2U)
#error "PROJECT_RNG_SELF_TEST_WORD_COUNT must be at least 2"
#endif

#define PROJECT_LOG_MODULE_MAX_LENGTH  8U
#define PROJECT_LOG_QUEUE_LENGTH       24U
#define PROJECT_LOG_MESSAGE_MAX_LENGTH 192U
#define PROJECT_LOG_RECORD_SIZE        (PROJECT_LOG_MESSAGE_MAX_LENGTH + 8U)
#define PROJECT_UART_TX_TIMEOUT_MS      50U

#define PROJECT_LOG_LEVEL_ERROR_VALUE 0U
#define PROJECT_LOG_LEVEL_WARN_VALUE  1U
#define PROJECT_LOG_LEVEL_INFO_VALUE  2U
#define PROJECT_LOG_LEVEL_DEBUG_VALUE 3U
#define PROJECT_LOG_LEVEL_NONE_VALUE  4U

/* Release 可通过 NDEBUG 或构建参数覆盖为 INFO；其他构建默认保留 DEBUG。 */
#ifndef PROJECT_LOG_LEVEL
#if defined(NDEBUG)
#define PROJECT_LOG_LEVEL PROJECT_LOG_LEVEL_INFO_VALUE
#else
#define PROJECT_LOG_LEVEL PROJECT_LOG_LEVEL_DEBUG_VALUE
#endif
#endif

#if (PROJECT_LOG_LEVEL > PROJECT_LOG_LEVEL_NONE_VALUE)
#error "PROJECT_LOG_LEVEL is invalid"
#endif

#define PROJECT_ENABLE_PRINTF_REDIRECT_TEST 0U

#endif /* PROJECT_CONFIG_H */
